### ISSUE TITLE
Live TV not working on Firestick

### ISSUE THREAD

**Issue by rutwik2499** [jimtape/new#1]
It's redirecting back to home screen on firestick but works fine on android phone, please fix this issue, thanks.

**Comment by homeamaan** [comment]
07-16 22:13:26.961  8231  8231 E AndroidRuntime: FATAL EXCEPTION: main
07-16 22:13:26.961  8231  8231 E AndroidRuntime: Process: com.offshore.pikachu, PID: 8231
07-16 22:13:26.961  8231  8231 E AndroidRuntime: java.lang.RuntimeException: Unable to resume activity {com.offshore.pikachu/com.offshore.pikachu.view.Player}: java.lang.NullPointerException: Attempt to invoke virtual method 'rc2 qc.Wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww()' on a null object reference
07-16 22:13:26.961  8231  8231 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3817)
07-16 22:13:26.961  8231  8231 E AndroidRuntime: 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3854)
07-16 22:13:26.961  8231  8231 E AndroidRuntime: 	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
07-16 22:13:26.961  8231  8231 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
07-16 22:13:26.961  8231  8231 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
07-16 22:13:26.961  8231  8231 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1824)
07-16 22:13:26.961  8231  8231 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
07-16 22:13:26.961  8231  8231 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:211)
07-16 22:13:26.961  8231  8231 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6740)
07-16 22:13:26.961  8231  8231 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-16 22:13:26.961  8231  8231 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
07-16 22:13:26.961  8231  8231 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
07-16 22:13:26.961  8231  8231 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'rc2 qc.Wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww()' on a null object reference
07-16 22:13:26.961  8231  8231 E AndroidRuntime: 	at com.offshore.pikachu.view.Player.onResume(SourceFile:3)
07-16 22:13:26.961  8231  8231 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1412)
07-16 22:13:26.961  8231  8231 E AndroidRuntime: 	at android.app.Activity.performResume(Activity.java:7335)
07-16 22:13:26.961  8231  8231 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3803)
07-16 22:13:26.961  8231  8231 E AndroidRuntime: 	... 11 more

These are the exact logs when the player activity is crashing

**Comment by hydroxd** [comment]
> It's redirecting back to home screen on firestick but works fine on android phone, please fix this issue, thanks.

yup facing the same problem here, started happening after the new update, do you have the link to their official website or their telegram channel?

**Comment by imurreflection** [comment]
Same issue on v 77. None of the movies/series are playing now. Also,app is crashing frequently. This is on Android TV.

**Comment by imurreflection** [comment]
Can you reply or you would like us to stop reporting issues???

**Comment by hydroxd** [comment]
> Can you reply or you would like us to stop reporting issues???

it is fixed now in v78 update it👍

**Comment by rutwik2499** [comment]
> > Can you reply or you would like us to stop reporting issues???
> 
> it is fixed now in v78 update it👍

where's the update? i can't seem to find it in this repo.

**Comment by imurreflection** [comment]
@hydroxd Thank you Mate.

**Comment by imurreflection** [comment]
@rutwik2499 it's an app update..not there in repo

**Comment by hydroxd** [comment]
> @hydroxd Thank you Mate.

welcome🙏
